import { AuthProvider } from "./Providers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Lean Six Sigma",
  description: "Generated by Lean Six Sigma",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          WebkitTextSizeAdjust: "100%",
          MozTextSizeAdjust: "100%",
          textSizeAdjust: "100%",
        }}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}